### ISSUE TITLE
HI,I would like to ask how to start a local Chrome web driver instead of a remote one

### ISSUE THREAD

**Issue by afishpro** [Nosferican/WebDriver.jl#12]
I read the document and didn't understand the local usage process

**Comment by Nosferican** [comment]
Could you add more details to what you didn't understand and what you have tried?

**Comment by afishpro** [comment]
Sorry to reply late
My current development environment is like this. I downloaded chromedriver and put it in the same directory as my JL file. At this time, I want to initialize the chromedriver and perform various operations.

**Comment by Nosferican** [comment]
I wouldn't expect that to work. Do you have access to Docker? If so, you can at least try the method in the documentation which is the one I used. I am sure there are other means to start the driver and connect to it, but I have only used Docker / Selenium which have worked fine and it's the recommended method for most packages (e.g., RSelenium also recommends using the Docker container).

**Comment by afishpro** [comment]
OK, I'll try your tutorial. Will your project be maintained for a long time

**Comment by Nosferican** [comment]
At least to the extend of the functionality I need / use. It might not get additional features but should be quite stable as the standard is a W3C recommendation so they don't make breaking changes lightly... Should be years before any breaking change.

**Comment by afishpro** [comment]
OK, thank you for your answer
