### ISSUE TITLE
Local Web Driver Support?

### ISSUE THREAD

**Issue by usmcamp0811** [Nosferican/WebDriver.jl#13]
Is there any way to make this use a local Web Driver? In Python I liked to have Selenium open a browser and I could interactively use the browser to test out the code as I wrote it. So far I haven't figured out how to do the comparable thing with the remote/Docker configuration you document in the readme.

**Comment by Nosferican** [comment]
If you are referring to having a browser in your computer being remotely controlled, I don't think I have done so through the Docker solution. You can pass the address of a local web driver instead of using the Docker solution (Docker is just easier most of the time). If using the Docker solution, you can use the `screenshot` function to capture what's going on in the browser being automated.

**Comment by usmcamp0811** [comment]
yea I am talking about being able to use `geckodriver` for Firefox or whatever the Chrome version is... to control a browser on your computer not in Docker so you can have the actual browser running and can interactively do things to debug as you write your scraper..

**Comment by dvetsch75** [comment]
@Nosferican could you explain the ```screenshot``` function please? Following the docs, I tried ```screenshot(session)``` but if I am working in the REPL it would still be nice to have something to look at. I also tried ```write("foo.png", screenshot(s))``` to no avail. 

I am way out of my depth here so if this is a dumb question I'll happily get rid of it.

**Comment by Nosferican** [comment]
This should work even if using the REPL
```
using WebDriver, Base64
capabilities = Capabilities("chrome")
wd = RemoteWebDriver(capabilities, host = "localhost", port = 4444, path = "") # Using Docker selenium/standalone-chrome:4
session = Session(wd)
navigate!(session, "https://google.com")
write("foo.png", base64decode(screenshot(session)))
```
Then I just look at the image with any software that can render PNG files.
